### ISSUE TITLE
Update product model

### ISSUE THREAD

**Issue by Dawnz** [Dawnz/amber-plumming-app-backend#12]
Based on what was done on the Integration, we would like the following changes
-change categoryID to categoryId
-price should be a floating point(confirm that this is the case)
-an imageUrl is required on every product

**Comment by tyndalesanjay** [comment]
- Price is now stated as a Double which allows you too add a floating point to the price.
- The field "categoryID" was changed to "categoryId".
- The Field "imageUrl" was added to the products model.
