### ISSUE TITLE
Should only Authorized users be able to update User Info?

### ISSUE THREAD

**Issue by rdwayne876** [Dawnz/amber-plumming-app-backend#8]
I can use the auth middleware to check if a valid bearer token is sent on the update request. This was only authenticated users with a valid access token will be able to update user info

**Comment by Dawnz** [comment]
how auth works with tokens is as follows
- a user is authenticated and given a token. this token will be stored and used to process all requests(middleware)
- a new request for a resource should have the request and the token that is not expired to authenticate the request
- this token with the request is usually sent as header information and is done via interceptors(front end)
- if the token is somehow expired they should not be able to get any resourse and should get a 401(unauthenticated) error
- they can always refresh the token by loging out and logging back in
